import { Separator } from "../components/ui/separator";

export const Privacy = () => {
  return (
    <div className="container mx-auto px-4 py-12">
      <article className="prose prose-slate max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>

        <div className="flex flex-col gap-1 text-sm text-muted-foreground mb-8">
          <div>Effective Date: [Insert Date]</div>
          <div>Last Updated: [Insert Date]</div>
        </div>

        <p className="mb-6">
          This Privacy Policy explains how AIChatBotGirlfriend.com ("we", "our",
          or "us") collects, uses, and protects your information when you use
          our website and AI companion services.
        </p>

        <Separator className="my-8" />

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            1. Information We Collect
          </h2>
          <p>We collect the following types of information:</p>

          <div className="space-y-6 mt-4">
            <div>
              <h3 className="text-xl font-medium mb-2">
                a. Account Information
              </h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Email address</li>
                <li>Name (optional)</li>
                <li>Authentication data (via Clerk or other auth providers)</li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-medium mb-2">b. Usage Data</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Chat messages you send to the AI</li>
                <li>Responses generated by the AI</li>
                <li>Timestamps, interaction logs, and activity history</li>
                <li>Device and browser information</li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-medium mb-2">c. Payment Data</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Subscription data (plan type, status)</li>
                <li>
                  Processed securely via Stripe — we do not store your full
                  payment information
                </li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-medium mb-2">d. Analytics</h3>
              <ul className="list-disc pl-6">
                <li>
                  We use services like Google Analytics or similar tools to
                  monitor traffic and usage patterns
                </li>
              </ul>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            2. How We Use Your Data
          </h2>
          <p>We use your data to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Provide and personalize your AI experience</li>
            <li>Maintain chat history (if enabled)</li>
            <li>Improve AI quality and system performance</li>
            <li>Monitor service usage and prevent abuse</li>
            <li>Process billing and manage subscriptions</li>
          </ul>
          <p className="mt-4">
            We do not sell or rent your personal data to third parties.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            3. Data Storage and Security
          </h2>
          <p>
            Your data is stored securely in cloud services (e.g. Supabase,
            Langfuse, Stripe) and is protected using industry-standard
            encryption and access control.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">4. Your Rights</h2>
          <p>You have the right to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Request access to your data</li>
            <li>Request correction or deletion of your personal data</li>
            <li>Withdraw consent and close your account</li>
          </ul>
          <p className="mt-4">
            You can manage or delete your data by contacting us at{" "}
            <a
              href="mailto:support@aichatbotgirlfriend.com"
              className="text-primary hover:underline"
            >
              support@aichatbotgirlfriend.com
            </a>
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            5. Cookies and Tracking
          </h2>
          <p>We may use cookies or similar tracking tools to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Keep you logged in</li>
            <li>Save preferences</li>
            <li>Analyze traffic and behavior</li>
          </ul>
          <p className="mt-4">
            You can control cookie preferences through your browser settings.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">6. AI Disclaimers</h2>
          <p>All conversations are stored for the purpose of:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Improving AI models</li>
            <li>Supporting user features like history</li>
            <li>Ensuring safety and moderation</li>
          </ul>
          <div className="mt-4 p-4 bg-muted rounded-lg">
            <p>
              Please avoid sharing sensitive or personally identifiable
              information in chats. The AI is not human and does not have
              consciousness or memory outside of your session.
            </p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            7. Third Parties We Work With
          </h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>Clerk – user authentication</li>
            <li>Stripe – payment processing</li>
            <li>Supabase – database and storage</li>
            <li>Langfuse – AI telemetry</li>
            <li>Google Analytics – usage analytics</li>
          </ul>
          <p className="mt-4">
            These services comply with industry standards for data privacy.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            8. Changes to This Policy
          </h2>
          <p>
            We may update this Privacy Policy. We will notify you via email or
            on-site notice if significant changes are made.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">9. Contact Us</h2>
          <p>
            If you have questions or concerns about this Privacy Policy, please
            contact:{" "}
            <a
              href="mailto:support@aichatbotgirlfriend.com"
              className="text-primary hover:underline"
            >
              support@aichatbotgirlfriend.com
            </a>
          </p>
        </section>

        <Separator className="my-8" />

        <div className="bg-muted p-6 rounded-lg flex items-center gap-3">
          <span className="text-2xl">🔒</span>
          <p>
            We are committed to protecting your privacy while offering a safe,
            immersive AI companion experience.
          </p>
        </div>
      </article>
    </div>
  );
};
