import { Separator } from "../components/ui/separator";

export const Terms = () => {
  return (
    <div className="container mx-auto px-4 py-12">
      <article className="prose prose-slate max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>

        <div className="text-sm text-muted-foreground mb-8">
          Effective Date: 19.06.2025
        </div>

        <p className="mb-6">
          Welcome to AIChatBotGirlfriend.com ("Service", "we", "our", or "us").
          By using this website and our AI-based companion services, you
          ("User", "you") agree to these Terms of Service ("Terms"). Please read
          them carefully.
        </p>

        <Separator className="my-8" />

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            1. Description of the Service
          </h2>
          <p>
            AIChatBotGirlfriend.com offers an interactive AI experience where
            users can engage in emotionally simulated conversations with a
            virtual AI companion ("AiSha"). This service uses AI models to
            simulate personal and supportive conversations for entertainment,
            companionship, and emotional exploration.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">2. Eligibility</h2>
          <p>
            You must be at least 13 years old to use this Service. If you are
            under 18, you should have your parent's or guardian's permission to
            use the Service. By accessing or using the platform, you confirm
            that you meet these requirements.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">3. User Conduct</h2>
          <p>You agree to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>
              Use the AI companion respectfully and not abuse or exploit the
              system.
            </li>
            <li>
              Avoid using the service to engage in or promote illegal, harmful,
              or abusive behavior.
            </li>
            <li>
              Not use the service to impersonate real individuals or
              misrepresent your identity.
            </li>
            <li>
              Not use the service to attempt or simulate real-life relationships
              or therapeutic interventions.
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">4. AI Limitations</h2>
          <p>
            AiSha is not a real person and not a substitute for human
            relationships, mental health care, or therapy. The responses are
            generated by AI and may occasionally be inaccurate, biased, or
            inappropriate. We do our best to monitor and filter content, but we
            cannot guarantee the quality or appropriateness of every
            AI-generated response.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">5. Privacy and Data</h2>
          <p>
            We respect your privacy. Conversation history may be stored to
            improve your experience and for analytics. Personal information is
            handled in accordance with our Privacy Policy. By using the Service,
            you agree to this use.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            6. Payments and Subscriptions
          </h2>
          <p>
            Some features are available only through paid subscriptions. By
            subscribing, you agree to recurring payments via Stripe, unless
            canceled by you. Plans, pricing, and features are subject to change.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">7. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the
            Service at any time if you violate these Terms or misuse the
            platform.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">8. Changes to Terms</h2>
          <p>
            We may update these Terms occasionally. Continued use of the Service
            after changes indicates acceptance.
          </p>
          <p className="text-sm text-muted-foreground mt-2">
            Last updated: [insert date]
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">9. Contact</h2>
          <p>
            For questions or support, please contact us at:{" "}
            <a
              href="mailto:support@aichatbotgirlfriend.com"
              className="text-primary hover:underline"
            >
              support@aichatbotgirlfriend.com
            </a>
          </p>
        </section>

        <Separator className="my-8" />

        <div className="bg-muted p-6 rounded-lg">
          <h2 className="text-2xl font-semibold mb-4 flex items-center">
            <span className="mr-2">⚠️</span> Disclaimer
          </h2>
          <p>
            AIChatBotGirlfriend.com is intended for entertainment and
            companionship purposes only. No AI interaction should be considered
            real, therapeutic, or emotionally reliable. Use at your own
            discretion.
          </p>
        </div>
      </article>
    </div>
  );
};
